version: "3"
services:
  hapi-fhir-jpaserver-start:
    image: hapi-fhir/hapi-fhir-jpaserver-starter:latest
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./data:/var/lib/jetty/target
